/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ffb4ab",
        "surface-variant": "#e1e3e4",
        "surface-container": "#edeeef",
        "on-surface-variant": "#5d3f3c",
        "tertiary-container": "#747474",
        "tertiary": "#5b5b5b",
        "on-tertiary-fixed-variant": "#474747",
        "secondary-container": "#9fc2fe",
        "on-error": "#ffffff",
        "inverse-surface": "#0a1128",
        "surface-dim": "#d9dadb",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#1f477b",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary-container": "#e31e24",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#fcfcfc",
        "primary": "#ba0013",
        "on-secondary-fixed": "#001b3c",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "surface-bright": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#93000d",
        "on-primary-container": "#fffafa",
        "on-secondary-container": "#294f83",
        "background": "#f8f9fa",
        "secondary": "#0a1128",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#a7c8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary-fixed-dim": "#ffb4ab",
        "surface-tint": "#c00014",
        "surface": "#f8f9fa",
        "secondary-fixed": "#d5e3ff",
        "on-tertiary-fixed": "#1b1b1b",
        "primary-fixed": "#ffdad6",
        "outline-variant": "#e7bdb8",
        "tertiary-fixed": "#e2e2e2",
        "outline": "#926f6b",
        "on-primary-fixed": "#410002"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1280px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
